# Generated by Django 6.0.6 on 2026-07-02 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HighScore',
        ),
    ]
