# Generated by Django 6.0.6 on 2026-07-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0002_delete_highscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=15)),
                ('Score', models.IntegerField()),
            ],
            options={
                'ordering': ['-Score'],
            },
        ),
    ]
