# Generated by Django 6.0.6 on 2026-07-06 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['-score']},
        ),
        migrations.RenameField(
            model_name='score',
            old_name='Score',
            new_name='score',
        ),
    ]
