# Generated by Django 6.0.6 on 2026-07-09 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_score_options_rename_score_score_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={},
        ),
    ]
