# Generated by Django 6.0.6 on 2026-07-09 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_score_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['-score']},
        ),
    ]
